/*
 *  Copyright 2012 by Texas Instruments Incorporated.
 *
 */

/* this file was generated by xdc/bld/stddefs.xdt */
/*
 *  @(#) google.targets; 1, 0, 0,43; 4-27-2012 17:07:21; /db/ztree/library/trees/xdctargets/xdctargets-f21x/src/ xlibrary

 */

