/*
 *  Copyright 2012 by Texas Instruments Incorporated.
 *
 */

/* this file was generated by xdc/bld/stddefs.xdt */
/*
 *  @(#) microsoft.targets; 1, 0, 2, 0,534; 4-27-2012 17:07:28; /db/ztree/library/trees/xdctargets/xdctargets-f21x/src/ xlibrary

 */

